// Generates src/styles/palette.css: every colour scale of the shop, for the
// light theme ("Lagoon") and the dark theme ("Abyss").
//
//   node scripts/palette.mjs
//
// Each scale is built in OKLCH from one hue, so all colours share the same
// lightness steps. The light steps follow Tailwind's, so a class such as
// text-gray-500 keeps the contrast it always had. In the dark theme,
// backgrounds and text change separately (Tailwind lets backgroundColor and
// textColor use different values): pale backgrounds (50–300) turn into dark
// tints, while text turns light, and the mid tones used for buttons with
// white text (500–700) stay deep enough for that text.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Hue and peak chroma of each scale. Tailwind names are mapped to these in
// tailwind.config.js (blue → aqua, purple → violet, ...).
export const SCALES = {
  ink: { hue: 250, chroma: 0.03, neutral: true }, // cool grey with a hint of blue
  aqua: { hue: 212, chroma: 0.16 }, // the brand: pool water
  violet: { hue: 292, chroma: 0.22 }, // the "future" accent
  coral: { hue: 12, chroma: 0.19 },
  danger: { hue: 25, chroma: 0.21 },
  success: { hue: 158, chroma: 0.16 },
  amber: { hue: 80, chroma: 0.17 },
  orange: { hue: 50, chroma: 0.19 }
};

export const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

// Lightness per step
const LIGHT = {
  neutral: [0.985, 0.967, 0.928, 0.872, 0.707, 0.551, 0.446, 0.373, 0.278, 0.21, 0.145],
  chromatic: [0.975, 0.935, 0.885, 0.81, 0.72, 0.64, 0.55, 0.49, 0.425, 0.375, 0.28]
};
const DARK_FILL = {
  // 50 is the page, 100–300 raised surfaces and lines; 600–950 stay dark,
  // as they are used for dark panels with white text
  neutral: [0.155, 0.225, 0.265, 0.32, 0.43, 0.5, 0.37, 0.31, 0.26, 0.205, 0.17],
  chromatic: [0.215, 0.255, 0.31, 0.4, 0.62, 0.62, 0.55, 0.5, 0.43, 0.36, 0.28]
};
const DARK_TEXT = {
  // Everything reads light on the dark page; 400 is the dimmest
  neutral: [0.985, 0.96, 0.93, 0.87, 0.64, 0.7, 0.78, 0.85, 0.9, 0.945, 0.975],
  chromatic: [0.97, 0.945, 0.91, 0.86, 0.79, 0.78, 0.8, 0.84, 0.88, 0.915, 0.945]
};

// How much of the peak chroma each step gets: less at the extremes
const CHROMA = [0.18, 0.35, 0.55, 0.75, 0.92, 1, 1, 0.92, 0.8, 0.68, 0.55];
const DARK_TINT_CHROMA = [0.28, 0.34, 0.42, 0.55]; // 50–300 dark tints: muted

// OKLCH → linear sRGB (Björn Ottosson's OKLab)
const oklchToLinear = (l, c, h) => {
  const a = c * Math.cos((h * Math.PI) / 180);
  const b = c * Math.sin((h * Math.PI) / 180);
  const l_ = (l + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m_ = (l - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s_ = (l - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l_ - 3.3077115913 * m_ + 0.2309699292 * s_,
    -1.2684380046 * l_ + 2.6097574011 * m_ - 0.3413193965 * s_,
    -0.0041960863 * l_ - 0.7034186147 * m_ + 1.707614701 * s_
  ];
};

const toSrgb = (x) => (x <= 0.0031308 ? 12.92 * x : 1.055 * x ** (1 / 2.4) - 0.055);

// The most saturated in-gamut colour at this lightness and hue
const rgb = (l, c, h) => {
  let chroma = c;
  let lin = oklchToLinear(l, chroma, h);
  while (lin.some(v => v < 0 || v > 1) && chroma > 0) {
    chroma = Math.max(0, chroma - 0.002);
    lin = oklchToLinear(l, chroma, h);
  }
  return lin.map(v => Math.round(Math.min(1, Math.max(0, toSrgb(v))) * 255)).join(' ');
};

const scaleVars = (name, { hue, chroma, neutral }, theme) => {
  const kind = neutral ? 'neutral' : 'chromatic';
  return STEPS.flatMap((step, i) => {
    const peak = chroma * CHROMA[i];
    if (theme === 'light') {
      const value = rgb(LIGHT[kind][i], peak, hue);
      return [`  --${name}-${step}: ${value};`, `  --${name}-t${step}: ${value};`];
    }
    const tint = i < 4 ? chroma * DARK_TINT_CHROMA[i] : peak;
    return [
      `  --${name}-${step}: ${rgb(DARK_FILL[kind][i], tint, hue)};`,
      `  --${name}-t${step}: ${rgb(DARK_TEXT[kind][i], i < 4 ? chroma * 0.3 : peak * 0.75, hue)};`
    ];
  });
};

const block = (selector, theme) => [
  `${selector} {`,
  ...Object.entries(SCALES).flatMap(([name, scale]) => scaleVars(name, scale, theme)),
  '}'
].join('\n');

const css = [
  '/* Generated by scripts/palette.mjs: edit the hues there, then run',
  '   `node scripts/palette.mjs`. --<scale>-<step> are backgrounds, borders',
  '   and gradients; --<scale>-t<step> are text colours. .light and .dark',
  '   also force a theme on part of a page. */',
  block(':root, .light', 'light'),
  '',
  block('.dark', 'dark'),
  ''
].join('\n');

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = new URL('../src/styles/palette.css', import.meta.url);
  writeFileSync(out, css);
  console.log(`Wrote ${fileURLToPath(out)}`);
}
